version: '2'
services:
    jhipster_hello-mysql:
        container_name: jhipster_hello-mysql
        image: mysql:5.7.13
        # volumes:
        #     - ~/volumes/jhipster/jhipster_hello/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=jhipster_hello
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
